---
- name: Setup Apps
  hosts: localhost
  tags: system-pkgs
  vars:
    dockitems_remove:
      - Messages
      - Mail
      - Maps
      - Photos
      - FaceTime
      - Contacts
      - Reminders
      - Notes
      - TV
      - Music
      - Podcasts

    homebrew_taps:
      - homebrew/core
      - homebrew/cask
      - homebrew/cask-fonts
      - bamorim/tap
      - go-task/tap
      - heroku/brew
      - txn2/tap
      - tilt-dev/tap
      - norwoodj/tap
      - pulumi/tap

    homebrew_installed_packages:
      - asdf
      - aws-vault
      - awscli
      - bat
      - chezmoi
      - ctlptl
      - direnv
      - dust
      - fd
      - fzf
      - gh
      - gist
      - git-delta
      - glow
      - go-jsonnet
      - go-task
      - helm
      - helmfile
      - helm-docs
      - heroku
      - htop
      - httpie
      - hyperfine
      - jsonnet-bundler
      - kind
      - kubectx
      - kubefwd
      - kubernetes-cli
      - kubie
      - marp-cli
      - mkcert
      - neofetch
      - openjdk
      - postgresql
      - procs
      - pulumi
      - qrencode
      - ripgrep
      - rustup
      - shellcheck
      - starship
      - stern
      - swaks
      - tanka
      - tealdeer
      - terraform
      - thefuck
      - tmux
      - tokei
      - tilt
      - websocat
      - wxwidgets
      - crd2pulumi

    homebrew_cask_appdir: /Applications
    homebrew_cask_apps:
      - font-fira-code
      - 1password
      - 1password-cli
      - altair-graphql-client
      - android-sdk
      - aws-vpn-client
      - calibre
      - camunda-modeler
      - chromedriver
      - discord
      - docker
      - dotnet-sdk
      - dropbox
      - firefox
      - github
      - google-chrome
      - google-cloud-sdk
      - handbrake
      - insomnia
      - iterm2
      - jetbrains-toolbox
      - kitty
      - lens
      - microsoft-office
      - mmhmm
      - ngrok
      - poedit
      - postman
      - slack
      - slack
      - spotify
      - streamlabs-obs
      - telegram
      - vagrant
      - visual-studio-code
      - zoom

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.dock
      tags: ['dock']
- name: Install user apps & binaries
  hosts: localhost
  tags: system-pkgs
  tasks:
  - name: Create home bin directory
    command: 
      creates: ~/bin
      cmd: mkdir ~/bin
  - name: Install oh-my-zsh
    shell:
      creates: ~/.oh-my-zsh
      cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
