---
- name: Install Packages
  hosts: localhost
  tags: system-pkgs
  tasks:
  - name: Install base packages
    become: true
    apt:
      update_cache: yes
      name:
      - build-essential
      - ca-certificates
      - curl
      - curl
      - file
      - git
      - gnupg
      - inotify-tools
      - lsb-release
      - procps
      # Libraries for erlang
      - autoconf
      - m4
      - libncurses5-dev
      - libwxgtk3.0-gtk3-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libpng-dev
      - libssh-dev
      - unixodbc-dev
      - xsltproc
      - fop
      - libxml2-utils
      - libncurses-dev
      - openjdk-11-jdk
      - calibre
      - chromium-chromedriver
      - direnv
      - discord
      - ffmpeg
      - firefox
      - fonts-firacode
      - gimp
      - kitty
      - slack-desktop
      - telegram-desktop
      - vim
      - zsh
  - name: Install docker apt key
    become: true
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
  - name: Install docker apt repository
    become: true
    retries: 20
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
      filename: docker
  - name: Install Google Cloud apt key
    become: true
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
  - name: Install Google Cloud apt repository
    become: true
    retries: 20
    apt_repository:
      repo: deb https://packages.cloud.google.com/apt cloud-sdk main
      filename: google-cloud
  - name: Install packages from added repos
    become: true
    apt:
      update_cache: yes
      name:
      - docker-ce
      - docker-compose
      - google-cloud-cli
  - name: Check if Docker Desktop is installed
    shell: dpkg-query -W 'docker-desktop'
    ignore_errors: True
    register: docker_desktop_installed
  - name: Install Docker Desktop
    become: True
    apt:
      deb: https://desktop.docker.com/linux/main/amd64/docker-desktop-4.9.0-amd64.deb
  - name: Check if lens is installed
    shell: dpkg-query -W 'lens'
    ignore_errors: True
    register: lens_installed
  - name: Install Lens
    become: true
    apt:
      deb: https://api.k8slens.dev/binaries/Lens-5.5.3-latest.20220602.2.amd64.deb
    when: lens_installed is failed
  - name: Install linuxbrew
    shell:
      creates: /home/linuxbrew/.linuxbrew
      cmd: |
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  - name: Setup linuxbrew shellenv
    shell:
      cmd: |
        CMDTOADD="eval \"\$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)\""
        grep -qxF "$CMDTOADD" ~/.profile || echo "$CMDTOADD" >> ~/.profile
