---
- name: Install Packages
  hosts: localhost
  tags: system-pkgs
  tasks:
  - name: Install base packages
    become: true
    apt:
      update_cache: yes
      name:
      - build-essential
      - ca-certificates
      - curl
      - curl
      - file
      - git
      - gnupg
      - inotify-tools
      - lsb-release
      - procps
      # Libraries for erlang
      - autoconf
      - m4
      - libncurses5-dev
      - libwxgtk3.0-gtk3-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libpng-dev
      - libssh-dev
      - unixodbc-dev
      - xsltproc
      - fop
      - libxml2-utils
      - libncurses-dev
      - openjdk-11-jdk
  - name: Install docker apt key
    become: true
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
  - name: Install docker apt repository
    become: true
    retries: 20
    shell:
      cmd: | 
        add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu impish stable"
  - name: Install programs from APT
    become: true
    apt:
      update_cache: yes
      name:
      - ansible
      - calibre
      - chromium-chromedriver
      - containerd.io
      - direnv
      - discord
      - docker-ce
      - docker-ce-cli
      - ffmpeg
      - firefox
      - fonts-firacode
      - gimp
      - kitty
      - slack-desktop
      - telegram-desktop
      - vim
      - zsh
  - name: Check if lens is installed
    shell: dpkg-query -W 'lens'
    ignore_errors: True
    register: lens_installed
  - name: Install Lens
    become: true
    apt:
      deb: https://lens-binaries.s3-eu-west-1.amazonaws.com/ide/Lens-5.3.3-latest.20211223.1.amd64.deb
    when: lens_installed is failed
  - name: Install linuxbrew
    shell:
      creates: /home/linuxbrew/.linuxbrew
      cmd: |
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  - name: Setup linuxbrew shellenv
    shell:
      cmd: |
        CMDTOADD="eval \"\$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)\""
        grep -qxF "$CMDTOADD" ~/.profile || echo "$CMDTOADD" >> ~/.profile
  - name: Install brew taps
    community.general.homebrew_tap:
      name:
      - go-task/tap
      - heroku/brew
      - txn2/tap
      - tilt-dev/tap
      - norwoodj/tap
  - name: Install brew packages
    community.general.homebrew:
      path: "/home/linuxbrew/.linuxbrew/bin"
      name:
      - asdf
      - awscli
      - bat
      - chezmoi
      - ctlptl
      - docker-compose
      - dust
      - fd
      - fzf
      - gh
      - gist
      - git-delta
      - go-jsonnet
      - go-task
      - helm
      - helm-docs
      - helmfile
      - heroku
      - htop
      - httpie
      - jsonnet-bundler
      - kind
      - kubectx
      - kubefwd
      - kubernetes-cli
      - kubie
      - marp-cli
      - mkcert
      - neofetch
      - postgresql
      - procs
      - pulumi
      - qrencode
      - ripgrep
      - rustup
      - starship
      - stern
      - tealdeer
      - terraform
      - thefuck
      - tilt
      - tmux
      - tokei
      - websocat
- name: Install user apps & binaries
  hosts: localhost
  tags: user-apps
  tasks:
  - name: Install flatpacks packages
    community.general.flatpak:
      method: user
      name:
      - us.zoom.Zoom
      - com.spotify.Client
      - rest.insomnia.Insomnia
      - com.getpostman.Postman
  - name: Create home bin directory
    command: 
      creates: ~/bin
      cmd: mkdir ~/bin
  - name: Install oh-my-zsh
    shell:
      creates: ~/.oh-my-zsh
      cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  - name: Install loft
    shell:
      creates: ~/bin/loft
      chdir: ~/bin
      cmd: |
        curl -s -L "https://github.com/loft-sh/loft/releases/latest" | sed -nE 's!.*"([^"]*loft-linux-amd64)".*!https://github.com\1!p' | xargs -n 1 curl -L -o loft
        chmod +x loft
  - name: Install crd2pulumi
    shell:
      creates: ~/bin/crd2pulumi
      chdir: ~/bin
      cmd: |
        gzdir=$(mktemp -d)
        curl -SL https://github.com/pulumi/crd2pulumi/releases/download/v1.0.10/crd2pulumi-v1.0.10-linux-amd64.tar.gz -o "$gzdir/crd2pulumi.tar.gz"
        tar -xzvf "$gzdir/crd2pulumi.tar.gz" crd2pulumi
  - name: Install 1password-cli
    shell:
      creates: ~/bin/op
      chdir: ~/bin
      cmd: |
        tmpdir=$(mktemp -d)
        curl -SL https://cache.agilebits.com/dist/1P/op/pkg/v1.12.3/op_linux_amd64_v1.12.3.zip -o "$tmpdir/op.zip"
        unzip -p $tmpdir/op.zip op > op
        chmod +x op